openapi: 3.0.1
info:
  title: SampleIntegrationFlow
  version: v1
  description: |
    This API allows you to create sample records in the integration flow system.
    It provides endpoints for adding records and handling common errors such as
    "Too Many Requests" or "Internal Server Errors".
  x-targetEndpoint: >-
    https://dev-amazon-web-services-ncm543yw.it-cpi019-rt.cfapps.us10-002.hana.ondemand.com:443/http/sample
servers:
  - url: >-
      https://lab2dev.test.apimanagement.us10.hana.ondemand.com:443/1/sample
    description: Development server

tags:
  - name: Record routes
    description: Create mocked records through Cloud Integration

paths:
  /record:
    post:
      tags:
        - Record routes
      summary: Create a sample record
      operationId: createSampleRecord
      description: |
        This endpoint allows you to create a sample record in the system. 
        You need to provide a valid body and text parameter. 
        A successful request will return an ID for the created record.
      requestBody:
        description: Request payload to create a new record
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Catalog"
            examples:
              validRequest:
                summary: A valid request for creating a record
                value:
                  body: "valid_body"
                  text: "valid"
        required: true
      responses:
        "200":
          description: Operation completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                successResponse:
                  summary: Response for a successful record creation
                  value:
                    id: '1'
        "429":
          description: Too Many Requests - Throttling limit exceeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToManyRequests"
              examples:
                tooManyRequestsResponse:
                  summary: Response when the request limit has been exceeded
                  value:
                    message: "Too Many Requests"
                    status:
                      code: 429
                      text: "Your Quota Exceeded"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
              examples:
                internalErrorResponse:
                  summary: Response when an internal error occurs
                  value:
                    message: "Internal Error - Contact the administrator"
                    status:
                      statusCode: 500
                      message: "Internal Server Error"

components:
  schemas:
    Catalog:
      type: object
      properties:
        body:
          type: string
          description: The body content for the record, typically a description or data string.
          example: "valid_body"
        text:
          type: integer
          description: A numeric value associated with the record.
          example: 123
      required:
        - body
        - text

    Response:
      type: object
      properties:
        id:
          type: string
          description: The ID of the created record.
          example: '1'

    ToManyRequests:
      type: object
      properties:
        message:
          type: string
          description: Message indicating that the request limit has been exceeded.
          example: "Too Many Requests"
        status:
          type: object
          properties:
            code:
              type: integer
              description: HTTP status code for the error (429).
              example: 429
            text:
              type: string
              description: A human-readable message explaining the error.
              example: "Your Quota Exceeded"

    InternalServerError:
      type: object
      properties:
        message:
          type: string
          description: A message detailing the internal error.
          example: "Internal Error - Contact the administrator"
        status:
          type: object
          properties:
            statusCode:
              type: integer
              description: HTTP status code for the internal error (500).
              example: 500
            message:
              type: string
              description: A message explaining the internal error.
              example: "Internal Server Error"

  securitySchemes:
    apiKeyHeader:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - apiKeyHeader: []
