openapi: 3.0.1
info:
  title: SF ERP13 Catalog
  version: v1
  description: <p></p>
  x-targetEndpoint: >-
    https://grupo-real-qas.apimanagement.br10.hana.ondemand.com:443/v1/sf-erp13-catalog
servers:
  - url: >-
      https://grupo-real-qas.apimanagement.br10.hana.ondemand.com:443/v1/sf-erp13-catalog
tags:
  - name: Catalog
    description: Search for Flexibilized Prices
paths: 
  /:
    post:
      tags:
        - Catálogo
      summary: Search for Flexibilized Prices
      operationId: searchFlexibilizedPrices
      requestBody:
        description: Search for Flexibilized Prices
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Catalog"
        required: true
      responses:
        "200":
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatalogResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "429":
          description: To Many Requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToManyRequests"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
components:
  schemas:
    Catalog:
      type: object
      properties:
        idCliente:
          type: string
          example: 49932903000108
        idUnidade:
          type: string
          example: 1
        tipoPrazo:
          type: number
          example: 4
        seqPrazoCliente:
          type: number
          example: 2511
        skus:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: 1
              sku:
                type: string
                example: 138444801
        idGrupoEmpresa:
          type: string
          example: 1
    CatalogResponse:
      type: object
      properties:
        idCadastroCliente:
          type: string
          example: 49932903000108
        codigoFilial:
          type: string
          example: 1
        nomeFilial:
          type: string
          example: RMP-MTZ
        estoquesPrecoFlexibilizado:
          type: array
          items:
            type: object
            properties:
              sku:
                type: string
                example: 138444801
              nomeProduto:
                type: string
                example: INCORRETO
              quantidadeDisponivelEstoque:
                type: string
                example: 0
              precoFlexibilizado:
                type: string
                example: 0
              precoFlexibilizadoTributado:
                type: string
                example: 0
              descontoRCA:
                type: string
                example: 1.5
              quantidadeMinima:
                type: string
                example: 1
              disponivelVenda:
                type: string
                example: "N"
              motivoIndisponibilidade:
                type: string
                example: Item bloqueado para venda
              itemNovo:
                type: string
                example: "N"
              emPromocao:
                type: string
                example: "N"
        pipelinekey:
          type: string
          example: 65140f31-8642-4135-8f94-8aa901326619
    Unauthorized:
      type: object
      properties:
        fault:
          type: object
          properties:
            faultstring:
              type: string
              example: Access Token expired
            detail:
              type: object
              properties:
                errorcode:
                  type: string
                  example: keymanagement.service.access_token_expired
    ToManyRequests:
      type: object
      properties:
        message:
          type: string
          example: To Many Requests
        status:
          type: object
          properties:
            code:
              type: number
              example: 429
            text:
              type: string
              example: Your Quota Exceeded
    InternalServerError:
      type: object
      properties:
        message:
          type: string
          example: Internal Error - Contact the administrator
        status:
          type: object
          properties:
            code:
              type: number
              example: 500
            text:
              type: string
              example: Internal Server Error