openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users/{idCadastro}/{idLoja}:
    get:
      summary: Returns a list of users.
      parameters:
        - name: idCadastro
          in: path
          required: true
          description: ID do cadastro do usuário.
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: idLoja
          in: path
          required: true
          description: ID da loja do usuário.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
